version: 2
jobs:
  build:
    docker:
      - image: maven:3-jdk-8
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn clean compile

  test:
    docker:
      - image: maven:3-jdk-8
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn clean test
