version: 2
jobs:
  build:
    docker:
      - image: maven:3.6-jdk-8-alpine
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn clean compile

  test:
    docker:
      - image: maven:3.6-jdk-8-alpine
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn clean test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
        requires:
          - build